name: omni_file_manager
description: Omni - A powerful file manager for Android

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management & DI
  flutter_riverpod: ^2.5.1
  get_it: ^7.6.4
  go_router: ^13.2.0

  # Theming & UI
  google_fonts: ^6.2.1
  flutter_highlight: ^0.7.0

  # Media Players (Official & Verified)
  just_audio: ^0.9.36
  video_player: ^2.9.2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
