name: omni_file_manager
description: Omni - A powerful file manager for Android

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management & DI
  flutter_riverpod: ^2.5.1
  get_it: ^7.6.4
  go_router: ^13.2.0
  permission_handler: ^11.3.1

  # Theming & UI
  google_fonts: ^6.2.1
  flutter_highlight: ^0.7.0
  flutter_svg: ^2.0.10
  dynamic_color: 1.7.0

    # Media Players (Media Kit MPV Engine)
  just_audio: ^0.9.36
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: media_kit_video
  media_kit_libs_video: ^1.0.7


  # File System Utilities
  archive: ^3.4.10
  path: ^1.9.0
  pdfx: ^2.9.2                
  share_plus: ^10.0.0 

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
